apiVersion: apps/v1
kind: Deployment
metadata:
  name: age-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: age-calculator
  template:
    metadata:
      labels:
        app: age-calculator
    spec:
      containers:
      - name: age-calculator
        image: devopsproject774/age-calculator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
